name: metric_athlete_pod_ble
description: "BLE communication plugin for Metric Athlete GPS pods."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  plugin_platform_interface: ^2.0.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.pod_connector
        pluginClass: PodConnectorPlugin
      ios:
        pluginClass: PodConnectorPlugin
      macos:
        pluginClass: PodConnectorPlugin
      windows:
        pluginClass: PodConnectorPluginCApi
